name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
- title: 🚀 Features
  labels:
  - feature
- title: 🐛 Bug Fixes
  labels:
  - bug
- title: 🧰 Maintenance
  labels:
  - build
- title: 🌱 Dependency Updates
  labels:
  - dependency-update
exclude-labels:
- skip-changelog
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
