version = "3.10.7"

runner.dialect = Scala3

maxColumn = 120
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
lineEndings = preserve
includeCurlyBraceInSelectChains = false

align.preset = most
danglingParentheses.preset = true

docstrings.style = asterisk

spaces {
  inImportCurlyBraces = true
}

optIn.annotationNewlines = true

rewrite.rules = [SortImports, RedundantBraces]