version = "3.10.7"

runner.dialect = Scala213

docstrings.wrap = no

maxColumn = 120
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
lineEndings = preserve
includeCurlyBraceInSelectChains = false

align.preset = most
align.tokens."+" = [
  { code = "=",  owner = "Defn" },
  { code = "=>", owner = "Case" }
]

danglingParentheses.preset = true

docstrings.style = asterisk

spaces {
  inImportCurlyBraces = true
}

optIn.annotationNewlines = true

rewrite.rules = [SortImports, RedundantBraces]

fileOverride {
  "glob:**/scala-3/**" {
    runner.dialect = scala3
  }
  "glob:**/scala-2/**" {
    runner.dialect = scala213
  }
}