addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.5.6")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.8")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"   % "0.13.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "2.4.2")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"  % "1.11.2")
addSbtPlugin("dev.zio"            % "zio-sbt-website" % "0.4.7")
addSbtPlugin("dev.zio"            % "zio-sbt-ci"      % "0.4.7")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.8")
