addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.7")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"   % "0.12.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "2.1.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"       % "2.0.0")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"  % "1.5.12")
addSbtPlugin("dev.zio"            % "zio-sbt-website" % "0.3.10")
