addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.5.6")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"  % "1.9.0")
addSbtPlugin("com.github.sbt"     % "sbt-header"      % "5.11.0")
addSbtPlugin("dev.zio"            % "zio-sbt-website" % "0.6.1")
addSbtPlugin("dev.zio"            % "zio-sbt-ci"      % "0.6.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.7")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "2.4.4")
